language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t hellena1213/docker-react -f DockerFile.dev .

script:
    - docker run -e CI=true hellena1213/docker-react npm run test -- --coverage

#deploy:
#    provider:
#    region: ""
#    app: ""
#    env: ""
#    bucket_name:
#    bucket_path:
#    on:
#        branch: master
#    access_key_id: ""
#    secret_access_key:
#        secret: ""